### ISSUE TITLE
Only works the first time ?

### ISSUE THREAD

**Issue by TheRealMrKam** [TanmanG/LethalCompany-ForestGiantMotionsense#1]
Hello ! So i tested the mod only with dancetools (to make it spawn) and the giant don't see me if i don't move.
But once he saw me moving, even if he lost me and then he see me not moving, he is gonna chase me, is this intended ? He just recognises me or something ?

**Comment by Halomationdude14** [comment]
I'm experiencing the same issue and so are all of my friends who also play with me. Sometimes they will not be moving at all and when someone else moves, the giant is aggroed to the closest player regardless of whether they are moving or not.

**Comment by Gweneg** [comment]
Fixed in commit f632a9919a45edffab71ddfbed04defed300f8f4.
